services:
  - type: web
    name: bfhl-api
    env: node
    buildCommand: npm install
    startCommand: node backend.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true